name: Build and Deploy Sphinx Documentation

on:
  push:
    branches:
      - main  # Trigger workflow on push to the main branch
      - docs  # Trigger workflow on push to the docs branch

jobs:
  build:
    name: Build Sphinx Documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # Adjust the version to match your project

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.8.4"  # Use the desired Poetry version

      - name: Build HTML
        run: | 
          cd docs/
          make html

      - name: Run ghp-import
        run: | 
            ghp-import -n -p -f docs/_build/html